apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Configure your API Key or Credentials here...
  # ---
  # API Key:
  # api-key: your-api-key
  # - or -
  # Token:
  api-token: fake_token_ym9jr33kAHySk7gAL33FOXQxR5GrX
  #cloudflare-token: <token>