apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mydomainexample-io-certificate
  namespace: traefik
spec:
  secretName: mydomainexample-io-staging-tls
  issuerRef:
    name: letsencrypt-staging-clusterissuer
    kind: ClusterIssuer
  commonName: "*.mydomainexample.io"
  dnsNames:
  - "*.mydomainexample.io"