apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mydomainexample-oi-certificate
  namespace: default
spec:
  secretName: mydomainexample-io-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.mydomainexample.io"
  dnsNames:
  - "*.mydomainexample.io"